version: '3.8'
services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local